language: python
python:
  - "2.7"
branches:
  only:
    - master
install:
  - pip install -r requirements.txt
script:
  - python -m py_compile ./src/*.py
  - pylint ./src/*.py --disable=missing-docstring
